name = "RefractiveIndex"
uuid = "97a43521-7681-4ec2-835f-5b8ab7e7617e"
authors = ["Alex Ames <alexander.m.ames@gmail.com> and contributors"]
version = "0.1.3"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
HTTP = "0.9"
Interpolations = "0.13"
Memoize = "0.4"
Unitful = "1.6"
YAML = "0.4"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
